### ISSUE TITLE
ロゴ案の作成

### ISSUE THREAD

**Issue by takusumi0617** [takusumi0617/event_run_assist_tool#3]
アプリケーションで使用するロゴを作成。
あまり解像度は高くなくてOK

**Comment by sugasann** [comment]
![Uploading 無題289_20240726022722.png…]()

**Comment by sugasann** [comment]
![無題289_20240726022722](https://github.com/user-attachments/assets/d168e0da-91cf-43a9-8996-a5b2347d5c86)
